dbt_starrocks:
  outputs:
    dev:
      host: kube-starrocks-fe-proxy.warehouse.svc.cluster.local
      password: mbs_demo
      port: 9030
      schema: gold
      type: starrocks
      username: mbs_demo
      catalog: hive_catalog
      threads: 4
  target: dev
